### ISSUE TITLE
Issue: Round Corners

### ISSUE THREAD

**Issue by TheCre8r** [ColonelParrot/jscanify#2] opened 2023-04-21 23:22 UTC
It does not work well with pages with round corners. Otherwise works well.

**Comment by ColonelParrot** [comment] 2023-04-22 01:38
Hello!
Thanks for the report :)
Unfortunately, I'm very swamped at the moment, so patches will be very slowly released.

I'm working on fixing this issue. It would be very helpful if you could provide some sample data (no pressure if you can't). It would speed this process up greatly.

**Comment by ColonelParrot** [comment] 2023-05-09 02:19
Hey there,
Upon closer inspection, I've decided to close this as *wontfix* as I can't reproduce this issue.
If you could send an image containing a document with rounded corners that fails at detection, then I'll be happy to reopen this issue.

Also, I do have to weigh the benefits of detecting this over sacrificing accuracy of regular detection.

**Closed by ColonelParrot** 2023-05-09 02:19 UTC
Labels: enhancement

**Comment by TheCre8r** [comment] 2023-06-28 15:28
Sorry I have been extremely busy lately. This eBay listing shows some good examples of the cards I have.
https://www.ebay.com/itm/224056497141

**Comment by ColonelParrot** [comment] 2025-02-09 02:37
This functionality has been added in v1.3.0. My apologies for such a long delay :)

![Image](https://github.com/user-attachments/assets/f98fa704-e385-4188-9307-6b22b3b00ae4)
